[project]
name = "font-rename"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fonttools>=4.59.0",
]

[project.scripts]
font-rename = "font_rename.cli:main"

[build-system]
requires = ["uv_build>=0.8.5,<0.9.0"]
build-backend = "uv_build"
